package com.wenxt.base.sample.drools

import com.wenxt.base.sample.drools.DetailsModel;
import java.util.List;
import java.util.ArrayList;
rule "Not Eligible to Vote"
salience 1
	when
		details: DetailsModel(age > 100 || age < 18)
	then 
		System.out.println("Not Eligible to Vote");
		List<String> list = details.getMessage();
		    if (list == null) {
        list = new ArrayList<>();
    }
		list.add("Not Eligible to Vote. He/She is " + (Math.abs(18 - details.getAge())) + " years younger or older than the eligibility");
		details.setMessage(list);
	end
rule "Enter Correct Value"
salience 2
	when
		details: DetailsModel(age == 0)
	then
		List<String> list = details.getMessage();
		    if (list == null) {
        list = new ArrayList<>();
    }
		list.add("Please enter Correct age");
		details.setMessage(list);
	end
rule "UserName Length"
	when
		details: DetailsModel(userName.length() < 8)
	then
		List<String> list = details.getMessage();
		    if (list == null) {
        list = new ArrayList<>();
    }
		list.add("Please enter userName more than 8 letters");
		details.setMessage(list);
	end